name: reference

on:
  push:
    branches-ignore:
      - 'gh-pages'

env:
  GH_TOKEN_DISPATCH: ${{ secrets.GH_TOKEN_DISPATCH }}
  GH_TOKEN_PUSH: ${{ secrets.GH_TOKEN_PUSH }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Generate antora.yml
        run: ./gradlew :spring-security-docs:generateAntora
      - name: Push generated antora files to the spring-security-docs-generated
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: "spring-security/main" # The branch the action should deploy to.
          folder: "docs/build/generateAntora" # The folder the action should deploy.
          repository-name: "rwinch/spring-security-docs-generated"
          token: ${{ secrets.GH_TOKEN_PUSH }}
      - name: Dispatch Build Request
        run: ${GITHUB_WORKSPACE}/.github/actions/dispatch.sh 'rwinch/spring-reference' "$GH_TOKEN_DISPATCH"
